# Generated by Django 5.1.4 on 2025-07-02 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('display_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=200)),
                ('school_id', models.CharField(blank=True, default='', max_length=50)),
                ('role', models.CharField(default='', max_length=100)),
                ('razorpay_customer_id', models.CharField(default='', max_length=100)),
                ('plain_id', models.CharField(default='', max_length=100)),
                ('subscription_id', models.CharField(default='', max_length=100)),
                ('special_offers', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=100, unique=True)),
                ('color_scheme', models.JSONField(default=dict)),
                ('logos', models.JSONField(default=dict)),
                ('fonts', models.JSONField(default=dict)),
                ('theme_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=100, unique=True)),
                ('domain', models.CharField(max_length=100)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('otp', models.CharField(max_length=6)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('due_date', models.DateField()),
                ('payment_status', models.BooleanField(default=False)),
                ('frequency', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('school_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_id', models.CharField(max_length=50, unique=True)),
                ('theme_color', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('logo_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(default=dict)),
                ('school_website_details_dict', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('school_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolGeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=100, unique=True)),
                ('contact_info', models.JSONField(default=dict)),
                ('social_links', models.JSONField(default=dict)),
                ('footer_content', models.JSONField(default=dict)),
                ('basic_info', models.JSONField(default=dict)),
                ('seo_metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('parent_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=50)),
                ('admission_number', models.CharField(max_length=100, unique=True)),
                ('student_class', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('roll_number', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school_id', models.CharField(max_length=50)),
                ('address', models.JSONField(default=dict)),
                ('regular_fees', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schoolmate_app.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=15)),
                ('year', models.IntegerField(default=2025)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_type', models.CharField(choices=[('regular', 'Regular'), ('books', 'Books'), ('uniform', 'Uniform'), ('bag', 'Bag'), ('transport', 'Transport'), ('other', 'Other')], default='regular', max_length=50)),
                ('mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('card', 'Card'), ('cheque', 'Cheque'), ('wallet', 'Wallet')], max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='schoolmate_app.student')),
            ],
        ),
    ]
