# Generated by Django 5.1.4 on 2025-07-02 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='class_id',
        ),
    ]
