# Generated by Django 5.1.4 on 2025-06-19 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=15)),
                ('year', models.IntegerField(default=2025)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_type', models.CharField(choices=[('regular', 'Regular'), ('books', 'Books'), ('uniform', 'Uniform'), ('bag', 'Bag'), ('transport', 'Transport'), ('other', 'Other')], default='regular', max_length=50)),
                ('mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('card', 'Card'), ('cheque', 'Cheque'), ('wallet', 'Wallet')], max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='schoolmate_app.student')),
            ],
            options={
                'ordering': ['-year', 'month'],
                'unique_together': {('student', 'month', 'year', 'fee_type')},
            },
        ),
    ]
