# Generated by Django 5.1.4 on 2025-06-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feepayment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='feepayment',
            unique_together=set(),
        ),
    ]
