# Generated by Django 5.1.4 on 2025-06-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmate_app', '0002_feepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('otp', models.CharField(max_length=6)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
