# Generated by Django 5.1.4 on 2025-06-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmate_app', '0003_contentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=100, unique=True)),
                ('color_scheme', models.JSONField(default=dict)),
                ('logos', models.JSONField(default=dict)),
                ('fonts', models.JSONField(default=dict)),
                ('theme_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
