# Generated by Django 5.1.4 on 2025-07-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmate_app', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='school_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
