# Generated by Django 5.1.4 on 2025-06-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmate_app', '0004_brandingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=100, unique=True)),
                ('contact_info', models.JSONField(default=dict)),
                ('social_links', models.JSONField(default=dict)),
                ('footer_content', models.JSONField(default=dict)),
                ('basic_info', models.JSONField(default=dict)),
                ('seo_metadata', models.JSONField(default=dict)),
            ],
        ),
    ]
