# Generated by Django 5.1.4 on 2025-06-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmate_app', '0005_schoolgeneralsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='domain',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
