# Generated by Django 5.1.4 on 2025-06-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmate_app', '0006_contentblock_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='plain_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='domain',
            field=models.CharField(max_length=100),
        ),
    ]
