# Generated by Django 5.1.4 on 2025-06-26 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmate_app', '0007_user_customer_id_user_plain_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customer_id',
            new_name='razorpay_customer_id',
        ),
    ]
