# Generated by Django 5.1.4 on 2025-06-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmate_app', '0008_rename_customer_id_user_razorpay_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
